name: Ansible File Test

on:
  push:
    branch: [main]
  pull_request:
    branch: [main]

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p playbooks'
